In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Two numpy array of size 3 x 2 and 2 x 3
array1= np.array([[2,4,7],[5,8,4]])
array2= np.array([[8,-6],[9,3],[2,-9]])
print(array1)
print(array2)

[[2 4 7]
 [5 8 4]]
[[ 8 -6]
 [ 9  3]
 [ 2 -9]]


In [ ]:
#randomly initalize that array
array = np.random.rand(3,6)
print(array)

[[0.85761838 0.33779909 0.89594023 0.20165369 0.57525714 0.26805236]
 [0.63694889 0.56801213 0.38515565 0.46951371 0.20999925 0.68656103]
 [0.78885079 0.93021123 0.64384579 0.74594159 0.45168641 0.9055168 ]]


In [ ]:
#perform matrix multiplacation
mul = np.dot(array1, array2)
print(mul)

[[ 66 -63]
 [120 -42]]


In [ ]:
#perfrom element wise matrix multiplacation
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])):
    for k in range(len(array2)):
      res[i][j] += array1[i][k] * array2[k][j]

print(res)

[[66, -63], [120, -42]]


In [ ]:
#mean of first matrix
mean = np.mean(array1)
print(mean)

5.0


In [ ]:
main_data = pd.read_csv("mtcars.csv")

In [ ]:
del main_data['model']
#meancenter
meancenter = main_data.apply(lambda e:e - e.mean())
print(meancenter.head())

NameError: ignored